package_name: java
version: 0.11
license: GPLv2+
authors: [Bohuslav Kabrda <bkabrda@redhat.com>, Michal Srb <msrb@redhat.com>]
homepage: https://github.com/devassistant/dap-java
summary: Java assistants
bugreports: https://github.com/devassistant/dap-java/issues
dependencies:
  - common_args
  - eclipse
  - git
  - github
description: |
    Kickstarts new Java projects.

    Currently supports Maven and JavaServer Faces projects.
